In [2]:
import pandas as pd
from torch.utils.data import Dataset

In [66]:
path = "../data/cleaned_tom/ToM_test_HiExTi_hint.parquet"

tom_df = pd.read_parquet(path)
tom_df.shape

(8060, 8)

In [68]:
# question for the template
# story for the template

# Used in code
# data_source - used for selecting reward
# prompt for input
# reward_model (used for ground_truth)
# extra_info? doesn't seem to be used

tom_df.sample()

,prompt,answer,data_source,question,story,extra_info,ability,reward_model
463,[{'content': '<|im_start|>system You are a hel...,bucket,tomi,Where will Ethan look for the persimmon?,Olivia entered the basement. Ethan entered the...,"{'deception': None, 'infilled_story': None, 'i...",theory_of_mind,"{'ground_truth': 'bucket', 'style': 'rule'}"

In [63]:
# What does tokenizer return as attention_idx 
import transformers as T
import torch
model_name = "meta-llama/Llama-3.2-1B-Instruct"

#model = T.AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = T.AutoTokenizer.from_pretrained(model_name)

p = """"<|im_start|>system\nYou are a helpful assistant. The assistant first thinks about the reasoning process in the mind and then provides the user with the answer. The reasoning process and answer are enclosed within <think> </think> and <answer> </answer> tags, respectively, i.e., <think> reasoning process here </think><answer> answer here </answer>. Now the user asks you to solve a theory of mind reasoning problem. After thinking, when you finally reach a conclusion, clearly state your answer within <answer> </answer> tags.\nNote: You should assume the following.\n(1) An agent witnesses everything and every movement before exiting a room.\n(2) An agent A can infer another agent B's mental state only if A and B have been in the same room, or have private or public interactions.\n<|im_end|>\n<|im_start|>user\nRead the following story and answer the question. \nStory: Lucas entered the closet. Oliver entered the patio. Mila dislikes the sweater Oliver exited the patio. Mila entered the closet. The tie is in the treasure_chest. Mila exited the closet. Lucas moved the tie to the container. Lucas exited the closet. Mila entered the closet.\nQuestion:  Where is the tie really?\n<|im_end|>\n<|im_start|>assistant\n<think>I think this is good</think><|im_end|>"""

out = tokenizer(p, return_tensors='pt', add_special_tokens=False)

In [65]:
mask = out['attention_mask']

torch.clip(torch.cumsum(mask, dim=-1) - 1, min=0, max=None)

tensor([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
          14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
          28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
          42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
          56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
          70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
          98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
         112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
         126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
         140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
         154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
         168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181,
         182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
         196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209,
         210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223,
         224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237,
         238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251,
         252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265,
         266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279,
         280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293,
         294]])

In [69]:
negtom_df = pd.read_parquet("../../tomrl/NegotiationToM_Qwen-Qwen2.5-0.5B-Instruct.parquet")
negtom_df.shape

(8, 9)

In [73]:
negtom_df.sample()

,prompt_len,response_words,data_source,prompt,prompt_for_pp,ability,reward_model,metadata,answer_pp
3,316,22,tomi,[{'content': '<|im_start|>system You are a hel...,<|im_start|>system\nYou are a helpful research...,theory_of_mind,"{'ground_truth': 'If I only get 1 food, than I...","{'conv_id': 2, 'reward_model': {'ground_truth'...",6.285318

In [88]:
torch.tensor([0])

tensor([0])